markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Ramnath K
author: Ramnath Krishnamurthy
url: http://ramnath-k.github.io
description: Blog containing musings about computer vision and life from Ramnath
twitter: ramnath_cv
linkedin: ramnathkrishnamurthy
highlighter: pygments

